services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: backend/.env
    environment:
      - RP_ORIGIN=http://localhost
      - CORS_ORIGINS=http://localhost
    ports:
      - "9091:9090"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - API_URL=http://backend:9090
    ports:
      - "80:80"
    depends_on:
      - backend
